### ISSUE TITLE
How to use with GraphQL?

### ISSUE THREAD

**Issue by flayks** [pauloamgomes/Cockpit-MultipleCollectionLink#6]
It seems that querying a field created by Cockpit-MultipleCollectionLink is not super pleasing to Cockpit GraphQL.\
This simple example:
```graphql
siteSingleton {
    highlight {
        _id
    }
}
```
Just returns that error, even though the field "highlight" does exists:
```
{
  "errors": [
    {
      "message": "Cannot query field \"highlight\" on type \"siteSingleton\".",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ]
    }
  ]
}
```

Any idea how to use it properly?

PS: the plugin does work with the REST API, but I haven't found a way to make it work with the [GraphQL Cockpit plugin](https://github.com/agentejo/CockpitQL).

**Comment by pauloamgomes** [comment]
Hi @flayks 
I'm afraid that is not supported, unfortunately, Cockpit GraphQL implementation only works by default with default core fields. In order to have the custom field types definitions each addon needs to set the field definition (e.g. in similar way I'm doing on other addons like https://github.com/pauloamgomes/CockpitCMS-BetterSlugs/blob/master/cockpitql.php). However for the Multiple Collection Link the field definition is a bit more complex and never had the time to implement it.

**Comment by flayks** [comment]
Ha, bummer, I understand. That would be very helpful!
